# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('laboratorio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=30)),
                ('laboratorio', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='donacion',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuarios'),
        ),
    ]
