# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171118_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='laboratorio',
        ),
        migrations.AddField(
            model_name='donacion',
            name='medicamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Medicamento'),
            preserve_default=False,
        ),
    ]
