# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171118_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='medicamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Medicamento'),
        ),
    ]
