# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_medicamento_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='informacion',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
