# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_medicamento_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Medicamento'),
        ),
    ]
