# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171122_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
