# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_medicamento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('doctor', models.CharField(max_length=70)),
                ('cedula', models.CharField(max_length=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuarios')),
            ],
        ),
    ]
