# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_medicamento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
