# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_medicamento_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fechayhora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
