# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20171123_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='donador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Usuarios'),
            preserve_default=False,
        ),
    ]
